version: '3'
services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
  nodejs:
    build:
      context: ./interface-nodejs
    ports:
      - "8082:8082"
    links:
      -  mongo
    restart: unless-stopped
  mqttsubscriber:
    build:
      context: ./subscriber-mqtt
    ports:
      - "8083:8083"
    links:
      -  mongo
    restart: unless-stopped
    tty: true
  broker:
    build:
      context: ./broker-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"