version: '3'
services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
  nodejs:
    build:
      context: ./interface-nodejs
    ports:
      - "8082:8082"
    links:
      -  mongo
    restart: unless-stopped
    depends_on:
      - mongo
  subscriber:
    build:
      context: ./subscriber-mqtt
    links:
      -  mongo
    restart: unless-stopped
    tty: true
    depends_on:
      - mongo
  broker:
    build:
      context: ./broker-mqtt
    ports:
      - "1883:1883"
      - "9883:9883"
